steelbrain/atom-linter

lib/helpers.coffee, spec/helper-spec.coffee
Fixes #4 
/cc @atom-community/linter-contributors
/cc @AtomLinter/linter 
/cc @AtomLinter/owners 
This is an API breaking change, make sure you are not using this method anywhere.
=> Remove execFilePath method

lib/helpers.coffee
Passing in custom options without process.env.OS to fix issues on windows machines.
I'm creating a copy of the process.env by using JSON.parse(JSON.stringify(process.env)), which is a bit ugly. I can change that if you know of a cleaner way to do it.
=> Fixed linter on windows machines

lib/helpers.coffee, spec/helper-spec.coffee
Pass the `options` object along to `BufferedProcess`.  
- Fixes #28
=> Pass options to BufferedProcess

lib/helpers.coffee, spec/helper-spec.coffee
some of the linters provides an column of the reported line. 
The helper should support this parameter to avoid refactoring of this lines on each linter plugin.
=> accept optional start of column for rangeFromLineNumber

lib/helpers.coffee, spec/helper-spec.coffee
Calling `findFile('/a/path/that/does/not/exist', '.gitignore')` located
`.gitignore` of the atom-linter module.
This happened since the first item of `startDir.split(path.sep)` is `""`
and `fs.accessSync('.gitignore', fs.R_OK)` yielded the file from the
module.
=> findFile: do not find files in the module dir

CHANGELOG.md, lib/helpers.coffee, package.json, spec/helper-spec.coffee
Ranges are 0-based, not 1-based
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/atom-linter/52)
=> Fix rangeFromLineNumber

CHANGELOG.md, README.md, lib/helpers.coffee, spec/helper-spec.coffee
It'll allow providers to create html elements with events that survive a clone.
Reason:
We clone the elements in linter because we can't show one element and on both bubble and bottom panel. It'll be removed from the other place if we remove it from one place. As a workaround we clone the given html element and show it there, but that way all the events attached to that element are lost. This will allow package authors to create elements with events that survive a clone
ToDo:
=> Add helpers.createElement

CHANGELOG.md, lib/helpers.coffee, spec/helper-spec.coffee
This patch handles colStart when it is greater than line length, throwing an exception.
Another solution may be to set colStart equals to the line length (defensive approach), but I think it is better to warning the programmer the parameter passed is wrong.
(I didn't squash the commits because I made the job via web - I am out of town)
=> Handle invalid colstart

CHANGELOG.md, lib/helpers.coffee, spec/fixtures/mixedIndent.js, spec/helper-spec.coffee
Previously it was assumed that a file had consistent indentation, this fixes that incorrect assumption.
Fixes #63.
=> Handle mixed indentation

CHANGELOG.md, lib/helpers.coffee, spec/helper-spec.coffee
Turns out that the Range() end point is exclusive, not inclusive as was previously assumed.
=> Fix the range end point

lib/helpers.js, src/helpers.js
If an absolute path (e.g. `/foo/bar`) is given to the current implementation of `findFile`, the root directory is stripped out and will not be checked.  Rather, it checks:
- `/foo/bar`
- `/foo`
The changes in this PR should cause it to check:
- `/foo/bar`
- `/foo`
- `/`
=> Check root dir

CHANGELOG.md, lib/helpers.js, src/helpers.js
Because it never really looked for just files, it looks for anything with that name that's readable
We still export the previous functions as aliases to new ones, so Yes that's backward compatible
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/atom-linter/68)
=> Rename findFile$ to find$

README.md
Apparently when this got added back in v3.2.0 the documentation was never updated.
=> Document colStart parameter to rangeFromLineNumber

lib/helpers.js, package.json, src/helpers.js
cc @Arcanemagus 
Pros
- It's backward compatible
- It's lightweight, so the tons of packages depending on this package that don't use it will enjoy it
Cons
- Not yet battle tested on our scale (it does have a test suite)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/atom-linter/98)
=> Use named-js-regexp instead of xregexp

lib/helpers.js, spec/helper-spec.js, src/helpers.js
When an invalid or no line number is given, return the entire first line instead of just the first character.
Fixes #87.
=> Return whole first line on error

lib/helpers.js, src/helpers.js
As of Atom v1.4.0 there is a built in function to validate whether an object is a TextEditor, move to using that if available.
Fixes #80.
=> Use the Atom API to validate TextEditor

.babelrc, CHANGELOG.md, package.json, src/helpers.js
We will not just be figuring out the `PATH` but all the tokens of keys or configurations the user might have set for applications in their rc files
=> Use consistent-env instead of consistent-path

README.md, package.json
=> Cleanup API in README

.eslintrc.json, spec/helper-spec.js, src/index.js
It turns out that the required import of the Range object is breaking in worker processes for some providers. Move back to a Range-compatible Array in order to remove this requirement.
Fixes https://github.com/AtomLinter/linter-eslint/issues/765.
=> Return Range-compatible Array from rangeFromLineNumber

package.json
The previous script didn't work on Windows. Move to using `rimraf` to delete the folder as it works wherever Node.js does.
=> Use rimraf for cross-platform clean script

README.md, spec/helper-spec.js, src/index.js
Rename the function `rangeFromLineNumber` to `generateRange`. It has accepted more than just a line number for several major versions, it's long past time the name was updated to account for that.
Fixes #150.
=> Rename rangeFromLineNumber to generateRange

decls/jasmine.js, package-lock.json, package.json, spec/helper-spec.js, src/index.js
This method has almost always required about as much work as it is doing after you run it to massage the results. There isn't any real point in keeping it around when no maintained provider is using it or is likely to in the future.
=> Deprecate parse method
