- lib/helpers.coffee
- spec/fixtures/something.js
- spec/helper-spec.coffee
> Add execNode method

- lib/helpers.coffee
Fixes https://github.com/AtomLinter/linter-jshint/issues/140
> Copy env from the process to the child

- lib/helpers.coffee
- spec/fixtures/something.js
- spec/fixtures/stderr.js
- spec/fixtures/stderr.sh
- spec/helper-spec.coffee
when we were expecting it to be on stdout
/cc @joefitzgerald @AtomLinter/linter
> Throw an error if we get something on stderr

- lib/helpers.coffee
Just like the title says
Fix #13
> Use Buffered{Node, }Process instead of vanilla child_process

- lib/helpers.coffee
> Make the env fix cross platform

- lib/helpers.coffee
- spec/helper-spec.coffee
> Add throwOnStdErr option

- lib/helpers.coffee
- package.json
Bumping a major version number so it doesn't break existing
> Throw errors by default

- lib/helpers.coffee
- spec/helper-spec.coffee
Fixes #27
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/atom-linter/29)
> Reject promise with error object instead of string

- lib/helpers.coffee
- spec/helper-spec.coffee
Be advised that it accepts 0 indexd line numbers.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/atom-linter/31)
> Add rangeFromLineNumber method

- lib/helpers.coffee
- spec/fixtures/both.js
- spec/helper-spec.coffee
Fixes https://github.com/AtomLinter/atom-linter/issues/33
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/atom-linter/37)
> Add support for capturing both streams

- lib/helpers.coffee
- package.json
- spec/helper-spec.coffee
Fixes https://github.com/AtomLinter/atom-linter/issues/30
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/atom-linter/39)
> Add temp file method

- lib/helpers.coffee
See discussion at https://github.com/AtomLinter/atom-linter/pull/39
Needed for https://github.com/AtomLinter/linter-pylint/pull/55
> Fix reference to undefined object `cleanupCallback`

- package.json
So, `npm test` should execute the tests.
> The script can be tested

- lib/helpers.coffee
- spec/helper-spec.coffee
Fixes #44
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/atom-linter/47)
> Show nicer EACCES error

- CHANGELOG.md
- README.md
- lib/helpers.coffee
- spec/helper-spec.coffee
Beep Beep.
Fixes #42
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/atom-linter/49)
> Add flags attribute to parse options

- .travis.yml
Beep Boop
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/atom-linter/50)
> Tweak travis a bit

- lib/helpers.coffee
Beep Beep
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/atom-linter/51)
> Future proof

- lib/helpers.coffee
Fixes #54
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/atom-linter/55)
> Make specs work with latest atom

- CHANGELOG.md
- lib/helpers.coffee
- package.json
- spec/helper-spec.coffee
Verify that lineNumber and colStart are numbers with values of at least 0.
Fixes #59.
> Verify rangeFromLineNumber inputs

- CHANGELOG.md
- lib/helpers.coffee
- spec/helper-spec.coffee
Verify that the lineNumber provided is not past the end of the buffer provided.
> Verify lineNumber

- CHANGELOG.md
- README.md
- lib/helpers.coffee
- spec/helper-spec.coffee
cc @kepler0 @noseglid @Arcanemagus @SpainTrain
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/atom-linter/66)
> Add findFileAsync helper

- lib/helpers.js
- src/helpers.js
Fixes #71
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/atom-linter/72)
> Use commonjs exports instead of ES6 exports

- CHANGELOG.md
- lib/helpers.js
- package.json
- spec/helper-spec.coffee
- src/helpers.js
Fixes #70
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/atom-linter/73)
> Remove backward compatibility

- CHANGELOG.md
- package.json
Beep Beep
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/atom-linter/74)
> Upgrade xregexp

- CHANGELOG.md
- lib/helpers.js
- spec/helper-spec.coffee
- src/helpers.js
Improves performance, works the same
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/atom-linter/75)
> Add cached find

- CHANGELOG.md
- README.md
- lib/helpers.js
- package.json
- src/helpers.js
Now peeps can clear cache using `Helpers.FindCache.clear()`
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/atom-linter/76)
> Export cache object

- CHANGELOG.md
- lib/helpers.js
- package.json
- src/helpers.js
Fixes AtomLinter/atom-linter#62
Closes https://github.com/AtomLinter/linter-pep8/pull/27
Closes https://github.com/AtomLinter/linter-shellcheck/pull/35
cc @Arcanemagus @SpainTrain @lexicalunit
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/atom-linter/86)
> Use consistent-path

- lib/helpers.js
- src/helpers.js
No API changed, just beautified some internals
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/atom-linter/88)
> Simplify tempFile method

- CHANGELOG.md
- README.md
- lib/helpers.js
- spec/helper-spec.coffee
- src/helpers.js
Thank you @andystanton for the idea and code POC :bow:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/atom-linter/89)
> Add tempFiles helper

- README.md
- lib/helpers.js
- spec/helper-spec.coffee
- src/helpers.js
Reason: Github code search shows **nobody** was using it
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/atom-linter/91)
> Remove createElement API

- CHANGELOG.md
- README.md
Beep Beep
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/atom-linter/92)
> Fix some typos

- package.json
:facepalm:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/atom-linter/93)
> Upgrade consistent-path

- CHANGELOG.md
- lib/helpers.js
- src/helpers.js
@steak3 pointed it out in #94
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/atom-linter/95)
> Do not modify process.env

- package.json
http://greenkeeper.io/
Merging this in, because why not :wink:.
> chore(package): update consistent-path to version 1.0.3

- CHANGELOG.md
- lib/helpers.js
- spec/helper-spec.coffee
- src/helpers.js
cc @Arcanemagus 
Fixes https://github.com/AtomLinter/linter-pep257/issues/29
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/atom-linter/99)
> Do not force g flag

- CHANGELOG.md
- src/helpers.js
> Make module work in runtimes without  module

- CHANGELOG.md
- README.md
- spec/fixtures/timeout.js
- spec/helper-spec.js
- spec/spec-helpers.js
- src/helpers.js
Fixes https://github.com/AtomLinter/atom-linter/issues/81
> Add timeout to process execution

- CHANGELOG.md
- src/index.js
> Use a better way of exposing exec*

- CHANGELOG.md
- package.json
> Bump sb-exec

- CHANGELOG.md
- spec/helper-spec.js
- src/index.js
> Enhance rangeFromLineNumber behavior

- CHANGELOG.md
- package.json
- spec/helper-spec.js
- src/index.js
> Return Range from rangeFromLineNumber

- CHANGELOG.md
- package.json
> Bump sb-exec@3.x

- CHANGELOG.md
- spec/helper-spec.js
- src/helpers.js
- src/index.js
> Handle ENOENT properly

- CHANGELOG.md
- spec/helper-spec.js
- src/helpers.js
> Restore 10 seconds timeout

- CHANGELOG.md
- README.md
- spec/fixtures/wait-2-seconds.js
- spec/helper-spec.js
- src/helpers.js
> Unique spawning

- README.md
> Add docs for file/scoped linter providers with uniqueKey

- package-lock.json
- package.json
- spec/helper-spec.js
> Update flow-bin to version 0.53.0 🚀

- circle.yml
- package.json
This PR migrates Circle Ci configuration to V2 and fixes the actual building process problems.
> V2 CircleCi configuration
